RamlDocumentNode (Start: 11 , End: 333, On: input.raml, Source: SYObjectNode)
    KeyValueNodeImpl (Start: 11 , End: 21, On: input.raml)
        SYStringNode: "title" (Start: 11 , End: 16, On: input.raml)
        OverlayableObjectNodeImpl (Start: 18 , End: 21, On: input.raml, Source: SYStringNode)
            KeyValueNodeImpl (Start: 11 , End: 21, On: input.raml)
                StringNodeImpl: "value" (Start: -1 , End: -1)
                OverlayableStringNode: "API" (Start: -1 , End: -1)
    KeyValueNodeImpl (Start: 23 , End: 46, On: input.raml)
        SYStringNode: "baseUri" (Start: 23 , End: 30, On: input.raml)
        ObjectNodeImpl (Start: 32 , End: 46, On: input.raml, Source: SYStringNode)
            KeyValueNodeImpl (Start: -1 , End: 46)
                StringNodeImpl: "value" (Start: -1 , End: -1)
                SYStringNode: "/some/base/uri" (Start: 32 , End: 46, On: input.raml, Source: SYStringNode)
    ResourceNode (Start: 48 , End: 305, On: input.raml, Source: KeyValueNodeImpl)
        SYStringNode: "/someChildUri" (Start: 48 , End: 61, On: input.raml)
        SYObjectNode (Start: 65 , End: 305, On: input.raml)
            MethodNode (Start: 65 , End: 190, On: input.raml, Source: KeyValueNodeImpl)
                SYStringNode: "get" (Start: 65 , End: 68, On: input.raml)
                SYObjectNode (Start: 74 , End: 190, On: input.raml)
                    KeyValueNodeImpl (Start: 74 , End: 190, On: input.raml)
                        SYStringNode: "responses" (Start: 74 , End: 83, On: input.raml)
                        SYObjectNode (Start: 91 , End: 190, On: input.raml)
                            KeyValueNodeImpl (Start: 91 , End: 190, On: input.raml)
                                SYIntegerNode: 200 (Start: 91 , End: 94, On: input.raml)
                                SYObjectNode (Start: 104 , End: 190, On: input.raml)
                                    BodyNode (Start: 104 , End: 190, On: input.raml, Source: KeyValueNodeImpl)
                                        SYStringNode: "body" (Start: 104 , End: 108, On: input.raml)
                                        SYObjectNode (Start: 120 , End: 190, On: input.raml)
                                            KeyValueNodeImpl (Start: 120 , End: 190, On: input.raml)
                                                SYStringNode: "application/xml" (Start: 120 , End: 135, On: input.raml)
                                                TypeDeclarationNode (Start: 149 , End: 190, On: input.raml, Source: SYObjectNode)
                                                    KeyValueNodeImpl (Start: 149 , End: 187, On: input.raml)
                                                        SYStringNode: "description" (Start: 149 , End: 160, On: input.raml)
                                                        OverlayableObjectNodeImpl (Start: 162 , End: 187, On: input.raml, Source: SYStringNode)
                                                            KeyValueNodeImpl (Start: 149 , End: 187, On: input.raml)
                                                                StringNodeImpl: "value" (Start: -1 , End: -1)
                                                                OverlayableStringNode: "some very useful resource" (Start: -1 , End: -1)
                                                    KeyValueNodeImpl (Start: -1 , End: -1)
                                                        StringNodeImpl: "type" (Start: -1 , End: -1)
                                                        NativeTypeExpressionNode: "any" (Start: -1 , End: -1)
                                                    KeyValueNodeImpl (Start: -1 , End: -1)
                                                        StringNodeImpl: "displayName" (Start: -1 , End: -1)
                                                        ObjectNodeImpl (Start: -1 , End: -1)
                                                            KeyValueNodeImpl (Start: -1 , End: 135)
                                                                StringNodeImpl: "value" (Start: -1 , End: -1)
                                                                SYStringNode: "application/xml" (Start: 120 , End: 135, On: input.raml, Source: SYStringNode)
                                    KeyValueNodeImpl (Start: -1 , End: -1)
                                        StringNodeImpl: "displayName" (Start: -1 , End: -1)
                                        ObjectNodeImpl (Start: -1 , End: -1)
                                            KeyValueNodeImpl (Start: -1 , End: 94)
                                                StringNodeImpl: "value" (Start: -1 , End: -1)
                                                SYIntegerNode: 200 (Start: 91 , End: 94, On: input.raml, Source: SYIntegerNode)
                    KeyValueNodeImpl (Start: -1 , End: -1)
                        StringNodeImpl: "displayName" (Start: -1 , End: -1)
                        ObjectNodeImpl (Start: -1 , End: -1)
                            KeyValueNodeImpl (Start: -1 , End: 68)
                                StringNodeImpl: "value" (Start: -1 , End: -1)
                                SYStringNode: "get" (Start: 65 , End: 68, On: input.raml, Source: SYStringNode)
            ResourceNode (Start: 190 , End: 305, On: input.raml, Source: KeyValueNodeImpl)
                SYStringNode: "/anotherChild" (Start: 190 , End: 203, On: input.raml)
                SYObjectNode (Start: 209 , End: 305, On: input.raml)
                    MethodNode (Start: 209 , End: 305, On: input.raml, Source: KeyValueNodeImpl)
                        SYStringNode: "put" (Start: 209 , End: 212, On: input.raml)
                        SYObjectNode (Start: 220 , End: 305, On: input.raml)
                            BodyNode (Start: 220 , End: 305, On: input.raml, Source: KeyValueNodeImpl)
                                SYStringNode: "body" (Start: 220 , End: 224, On: input.raml)
                                SYObjectNode (Start: 234 , End: 305, On: input.raml)
                                    KeyValueNodeImpl (Start: 234 , End: 305, On: input.raml)
                                        SYStringNode: "application/json" (Start: 234 , End: 250, On: input.raml)
                                        TypeDeclarationNode (Start: 262 , End: 305, On: input.raml, Source: SYObjectNode)
                                            KeyValueNodeImpl (Start: 262 , End: 303, On: input.raml)
                                                SYStringNode: "description" (Start: 262 , End: 273, On: input.raml)
                                                OverlayableObjectNodeImpl (Start: 275 , End: 303, On: input.raml, Source: SYStringNode)
                                                    KeyValueNodeImpl (Start: 262 , End: 303, On: input.raml)
                                                        StringNodeImpl: "value" (Start: -1 , End: -1)
                                                        OverlayableStringNode: "another very useful resource" (Start: -1 , End: -1)
                                            KeyValueNodeImpl (Start: -1 , End: -1)
                                                StringNodeImpl: "type" (Start: -1 , End: -1)
                                                NativeTypeExpressionNode: "any" (Start: -1 , End: -1)
                                            KeyValueNodeImpl (Start: -1 , End: -1)
                                                StringNodeImpl: "displayName" (Start: -1 , End: -1)
                                                ObjectNodeImpl (Start: -1 , End: -1)
                                                    KeyValueNodeImpl (Start: -1 , End: 250)
                                                        StringNodeImpl: "value" (Start: -1 , End: -1)
                                                        SYStringNode: "application/json" (Start: 234 , End: 250, On: input.raml, Source: SYStringNode)
                            KeyValueNodeImpl (Start: -1 , End: -1)
                                StringNodeImpl: "displayName" (Start: -1 , End: -1)
                                ObjectNodeImpl (Start: -1 , End: -1)
                                    KeyValueNodeImpl (Start: -1 , End: 212)
                                        StringNodeImpl: "value" (Start: -1 , End: -1)
                                        SYStringNode: "put" (Start: 209 , End: 212, On: input.raml, Source: SYStringNode)
                    KeyValueNodeImpl (Start: -1 , End: -1)
                        StringNodeImpl: "displayName" (Start: -1 , End: -1)
                        ObjectNodeImpl (Start: -1 , End: -1)
                            KeyValueNodeImpl (Start: -1 , End: 203)
                                StringNodeImpl: "value" (Start: -1 , End: -1)
                                SYStringNode: "/anotherChild" (Start: 190 , End: 203, On: input.raml, Source: SYStringNode)
            KeyValueNodeImpl (Start: -1 , End: -1)
                StringNodeImpl: "displayName" (Start: -1 , End: -1)
                ObjectNodeImpl (Start: -1 , End: -1)
                    KeyValueNodeImpl (Start: -1 , End: 61)
                        StringNodeImpl: "value" (Start: -1 , End: -1)
                        SYStringNode: "/someChildUri" (Start: 48 , End: 61, On: input.raml, Source: SYStringNode)
    ErrorNode: "The path /someChildUri/anotherChild was already defined." (Start: 305 , End: 332, On: input.raml, Source: ResourceNode)
        SYStringNode: "/someChildUri/anotherChild" (Start: 305 , End: 331, On: input.raml)
        SYNullNode (Start: 332 , End: 332, On: input.raml)
