#%RAML 1.0
title: My API with Types

types:
    one:
        type: string
        example:
            strict: false
            value: 12
    two:
        type: string
        example:
            strict: true
            value: 13
    three:
        type: string
        example: 14
