#%RAML 1.0 Trait

usage: Apply this to any method that needs to be secured
description: Some requests require authentication.
headers:
  access_token:
    description: Access Token
    example: 5757gh76
    required: true
