#%RAML 0.8
---
title: Sample API

/name:
    get:
        responses:
            200:
                body:
                    application/xml:
                        schema: !include refs/xsd-includer-nested.xsd
