#%RAML 0.8
---
title: Sample API
schemas:
    - name-schema: !include refs/xsd-includer-nested.xsd
/name:
    get:
        responses:
            200:
                body: !include refs/xsd-global.raml

