#%RAML 1.0
title: master
baseUri: http://api.com/master

types:
    User:
        properties:
            name: string
            age?: integer
        example:
            name: tato
            age?: 88
