#%RAML 1.0
title: My API With Types
types:
  comment:
    properties:
      name:
      comment: nil | string # equivalent to ->
                           # comment: string?
    example:
      name: Fred
      comment: # Providing a value or not providing a value here is allowed.