#%RAML 1.0 DataType

type: object
description: Simple address
properties:
  street:
    type: string
    description: Street and number
  zipCode:
    type: string
    description: Street and number
  city:
    type: string
    description: The city
  country:
    type: string
    description: The city
