#%RAML 1.0
title: simple object
types:
  root:
    properties:
      age: number
      children:
        type: number
        enum: [2, 3, 4, 5]
      averageAgeOfChildren:
        type: number
        enum: [6, 6.5, 7]
