#%RAML 1.0
title: Data type demo. Nothing really useful

types:
  MyString: string
  MyType: !include my-type.raml

/companies:
  post:
    body:
      application/json:
        type: MyType
        example: !include my-type-example.json