#%RAML 1.0

# this bug existed before the change
title: API Manager
mediaType: application/json


resourceTypes:
  collection:
    post:
      body:
        application/json:
          type: object
          properties:
            melli: number


/tiers:
  type: collection
  post:
    body:
      application/json:
        type: string