#%RAML 1.0 SecurityScheme

type: OAuth 2.0

settings:
  authorizationUri: http://example.com
  accessTokenUri: http://example.com
  authorizationGrants: http://example.com
  scopes: http://example.com