description: |
  OAuth 2.0 is a simple and secure authentication mechanism. It allows applications
  to acquire an access token for bitly via a quick redirect to the bitly site. Once
  an application has an access token, it can access a user's link metrics, and
  shorten links using that user's bitly account.
type: OAuth 2.0
describedBy: 
  headers: 
    Authorization: 
      description: |
        Used to send a valid OAuth 2 access token. Do not use together with
        the "access_token" query string parameter.
  queryParameters: 
    access_token: 
      description: |
        Used to send a valid OAuth 2 access token. Do not use together with
        the "Authorization" header
settings: 
  authorizationUri: https://bitly.com/oauth/authorize
  accessTokenUri: https://api-ssl.bitly.com/oauth/access_token
  authorizationGrants: [ authorization_code ]
