#%RAML 1.0
title: simple object
types:
  root:
    properties:
      age: number
/res:
  get:
    body:
      application/xml:
          type: root
          example: |
            <root>
              <age>27.21</age>
              <my-custom-xml>with-custom-value</my-custom-xml>
            </root>