#%RAML 1.0
title: Some API

types:
    DefaultMax:
      type: number
      minimum: 10.5
      examples:
        good: 10.5
        bad: 10.4
    DefaultMin:
      type: number
      maximum: 20.2
      examples:
        good: 20.2
        bad: 20.3
    ValidRange:
      type: number
      minimum: 2.5
      maximum: 2.5
    RangeError:
      type: number
      minimum: 3.4
      maximum: 2.9
    ValidMultiple:
      type: number
      minimum: 2.9
      maximum: 3.4
      multipleOf: 3.1
    InvalidMultiple:
      type: number
      minimum: 6.9
      maximum: 7.1
      multipleOf: 3.4
    OtherInvalidMultiple:
      type: number
      minimum: 2.9
      maximum: 3.5
      multipleOf: 4.1
    OtherValidMultiple:
      type: number
      minimum: 6.8
      maximum: 6.8
      multipleOf: 3.4
    MoreValidMultiple:
      type: number
      minimum: 6.8
      maximum: 6.9
    LastValidMultiple:
      type: number
      minimum: 6.7
      maximum: 6.8
    ValidEnum:
      type: number
      minimum: 3.2
      maximum: 5.1
      enum: [3.2, 5.1, 4.5]
    InvalidEnum:
      type: number
      minimum: 3.2
      maximum: 5.1
      enum: [3.2, 5.1, 6]
    ValidMultipleInEnum:
      type: number
      minimum: 2.5
      maximum: 12.6
      enum: [3.4, 6.8, 10.2]
    InvalidMultipleInEnum:
      type: number
      multipleOf: 3
      enum: [3.0, 6, 8.0]
