#%RAML 1.0
title: My API With Types
types:
  Person:
    type: object
    discriminator: kind # refers to the `kind` property of object `Person`
    properties:
      kind: 
        type: string # contains name of the kind of a `Person` instance
      name: 
        type: string
  Employee: # kind may equal to `Employee; default value for `discriminatorValue`
    type: Person
    properties:
      employeeId: 
        type: string
  User: # kind may equal to `User`; default value for `discriminatorValue`
    type: Person
    properties:
      userId: 
        type: string