#%RAML 1.0 Library
annotationTypes:
  important: nil
types:
  Url:
      type: string
      pattern:  |
        dd
  Entity:
      properties:
        type: object
        name: string
        id: number
        kind: string
        icon_url:
          type: Url[]
        createdAt: datetime
        modifiedAt: datetime
        createdBy?: User
  User:
      type: Entity
      properties:
        createdItems:
          type: Entity[]
