#%RAML 1.0 NamedExample

uses:
  lib: lib.raml

(lib.StringAnnotation): stringAnnotationValue
(lib.ObjectAnnotation):
  p1: stringValue
  p2: 10

strict: true
displayName: MyExample

value:
  property1: string value
  property2: 1