#%RAML 1.0
title: Types and traits issue.
mediaType: application/json
baseUri: http://foo.com

types:
  Stuff:
    properties:
      name: string

resourceTypes:
  base:
    get?:
      responses:
        200:
          body:
            application/json:
              type: array
              items: <<typeName>>

  base-collection:
    type:
      base:
        typeName: <<typeResponseCollectionItem200Get>>,
    get?:

  collection-readonly-get:
    type:
      base-collection:
        typeResponseCollectionItem200Get: <<typeResponseCollectionItem200Get>>
    get:

/parent:
  /child:
    type:
      collection-readonly-get:
        typeResponseCollectionItem200Get: Stuff