#%RAML 1.0

# JS parser should show an error like:
#               {âerrorâ : "no street or locality provided.â}
# JS-YAML: the stream contains non-printable characters at line 1, column 1 at (1, 1)
# Missing required property 'title' at (1, 10)

title: Address Matching API
version: V1
baseUri: http://some-place.org/api