#%RAML 1.0
title: hola
types:
    Readme:
        type: file
        fileTypes:
            - text/plain
            - text/csv
            - application/xml
        minLength: 1024
        maxLength: 2048