#%RAML 0.8
title: api title
version: v1
baseUri: http://base.uri/{version}/{param1}
mediaType: application/json
protocols: [HTTP, HTTPS]

baseUriParameters:
    param1:
        displayName: Param 1
        description: some description
        type: string
        maxLength: 10
        example: one

documentation:
    - title: doc title 1
      content: single line
    - title: doc title 2
      content: |
           multi
           line

schemas:
    - UserJson: |
          {
             "$schema": "http://json-schema.org/draft-04/schema",
             "type": "object",
             "properties": {
               "firstname":  { "type": "string" },
               "lastname":  { "type": "string" },
               "age":  { "type": "integer" }
             },
             "required": [ "firstname", "lastname" ]
          }

    - UserXml: |
       <xs:schema attributeFormDefault="unqualified"
                  elementFormDefault="qualified"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">
         <xs:element name="api-request">
           <xs:complexType>
             <xs:sequence>
               <xs:element type="xs:string" name="input"/>
             </xs:sequence>
           </xs:complexType>
         </xs:element>
       </xs:schema>
traits:
    one:
        description: method description from trait one
    two:
        description: method description from trait two

resourceTypes:
    first:
        usage: first usage

/top:
    description: top description
    type: first
    baseUriParameters:
        param1:
            description: resource override
            type: number
    get:
        baseUriParameters:
            param1:
                description: method override
                type: boolean
        description: get something
        queryParameters:
            order:
                default: asc
                repeat: true
                maxLength: 4
                example: desc
    post:
        description: post something
        body: &bodyPost
            application/json:
                schema: UserJson
                example: |
                    {
                        "firstname": "tato",
                        "lastname": "bores",
                        "age": 66
                    }
            application/xml:
                schema: UserXml
            multipart/form-data:
                formParameters:
                    description:
                        type: string
                    image:
                        type: file
            application/vnd.inline+json:
              schema: |
                {
                    "$schema": "http://json-schema.org/draft-03/schema",
                    "properties": {
                        "input": {
                            "required": false,
                            "type": "string"
                        }
                    },
                    "required": false,
                    "type": "object"
                }
        responses:
            200:
                body: *bodyPost
            400:

    /children:
        description: child description
        post:
            body:
                schema: UserJson
        /{childId}:
            uriParameters:
                childId:
                    type: string