#%RAML 1.0
title: Sample - Api
version: 1.0.0-SNAPSHOT
baseUri: http://api.samplehost.com

types:
  simpleObject:
    properties:
      first: string
  anotherObject:
    properties:
      second: string

/scalar:
  get:
    queryParameters:
      timeout:
        type: date-only
        required: true
        examples:
          theXml: <2019-09-09>
          theJson: |
            {2019-09-09}
/object:
  get:
    body:
      application/json:
        type: simpleObject
        examples:
          moreJson: |
            {"first": true}

/unionObject:
  get:
    body:
      application/json:
        type: simpleObject|anotherObject
        examples:
          moreJson: |
            {"first": true}

/unionNeverObject:
  get:
    body:
      application/json:
        type: boolean|integer
        examples:
          moreJson: |
            {hello}

/unionSometimesObject:
  get:
    body:
      application/json:
        type: string|simpleObject
        examples:
          moreJson: |
            <hello>


