  description: Change the severity of a specific logger.
  uriParameters:
    loggerName:
      description: |
        Name of the logger whose level is to be changed.
      type: string
      required: true
      example: "org.apache"
    newLevel:
      description: |
        The log level to be set.
      type: string
      required: true
      example: "DEBUG"
  get:
    queryParameters:
      createFlag:
        description: |
          Create logger iff it does not exist already.
        type: boolean
        required: false
        default: false
        example: false
      hoursToReset:
        description: |
          Delay until logger will be reset to original level (default = 24) for never use 0.
        type: integer
        required: false
        example: 2
    responses:
      200:
        body:
          text/plain:
           example: "#[com.canda.mulestac.logging.ChangeLogLevel.changeWithParams(flowVars.loggerName, flowVars.newLevel, message.inboundProperties.'http.query.params')]"
