#%RAML 1.0
title: Types 002.
version: v1
baseUri: https://example.com/raml
types:
  Player1: |
     {
       "type": "object",
       "properties": [
         {
           "name": "string"
         }
       ]
     }

schemas:
  Player2: |
     {
       "type": "object",
       "properties": [
         {
           "name": "string"
         }
       ]
     }
