#%RAML 1.0
title: xml body inline
/top:
    get:
        body:
            application/xml:
                xml:
                  name: Homer       
                properties:
                  firstname: string
                  lastname: string
                  age:
                      type: integer
                      minimum: 0
                      maximum: 144
