#%RAML 1.0
title: API

types:
  basetype:
      type: object
      properties:
        //: string

  subtype:
      type: basetype
      properties:
        attr: string
      example:
        attr: "a"