#%RAML 1.0
title: My API With Types
types:
  Initial_comments:
    type: object
    minProperties: 2
    properties:
      comment_id?: number
      initial_comments?: string
    example:
      initial_comments: mm
