#%RAML 1.0
title: My Date API
types:
  birthday:
    type: date-only # no implications about time or offset
    examples:
      good: 2015-05-23
      bad: 2016-13-33
      bad-2: 2016-12-33
      bad-3: 16-12-30
      bad-4: 20191-12-30
  lunchtime:
    type: time-only # no implications about date or offset
    examples:
      good: 12:30:00
      bad: 25:61:61
  fireworks:
    type: datetime-only # no implications about offset
    examples:
      good: 2015-07-04T21:00:00
      bad: 2015-13-33T25:61:61
  created:
    type: datetime
    examples:
      good: 2016-02-28T16:41:41.090Z
      bad: 2016-13-34T27:65:65.0901Z
    format: rfc3339 # the default, so no need to specify
  updated:
    type: datetime
    examples:
      good: 2016-02-28T16:41:41Z # secfrac is optional
      good1: 2016-02-28T16:41:41.08Z
      good2: 2016-02-28T16:41:41-08:30 # valid offset
      good3: 2016-02-28T16:41:41.09-08:30
      bad: 2016-02-28T16:41:41+8:30 # invalid offset
      bad2: 2016-02-27T16:41:11
      bad3: 2016-02-27T16:41
      bad4: 2016-02-27T16:41:1
    format: rfc3339 # the default, so no need to specify
  If-Modified-Since:
    type: datetime
    examples:
      good: Sun, 28 Feb 2016 16:41:41 GMT
      bad: San, 28 Feb 2016 16:41:41 GMT
    format: rfc2616 # this time it's required, otherwise, the example format is invalid
  union:
    type: date-only | time-only
    examples:
     time-only: 12:30:00
     date-only: 2015-05-23
