#%RAML 1.0
title: Example API
version: v1
resourceTypes:
  collection:
    description: The collection of users
    get:
      description: Get all users, optionally filtered
    post:
      description: Create a new user
    /hi:
/users:
  type: collection