#%RAML 1.0 Extension
extends: master.raml
types:
    User:
        type: object
        examples:
            pepo:
                name: pipo
                age: 77
            cacho:
                name: cacho
                age: 55
