queryParameters: 
  share_with_contacts: 
    description: Sets if your contacts on SlideShare can view the slideshow. Requires make_slideshow_private to be Y
  slideshow_tags: 
    description: Comma separated list of tags
  allow_embeds: 
    description: Sets if other websites should be allowed to embed the slideshow. Requires make_slideshow_private to be Y
  generate_secret_url: 
    description: Generate a secret URL for the slideshow. Requires make_slideshow_private to be Y
  make_slideshow_private: 
    description: Should be Y if you want to make the slideshow private. If this is not set, following tags will not be considered
  slideshow_title: 
    description: Title of the slideshow
    required: <<titleRequired>>
