queryParameters: 
  limit: 
    description: Specify the number of <<name>> to return
    type: integer
    minimum: 1
    example: 10
  offset: 
    description: specify offset
    type: integer
    minimum: 0
