#%RAML 1.0 Library

traits:
  orderby:
    queryParameters:
      orderby:
        description: Expression for determining what values are used to order the collection of Entries
        type: string
        required: false