#%RAML 1.0
title: Illustrating allowed targets
mediaType: application/json
annotationTypes:
  meta-invalid-target:
    allowedTargets: scalar
  meta-invalid-targets:
    allowedTargets: [ Resource, Action ]
