#%RAML 1.0
title: arrays
types:
  Person:
    properties:
      name: string
      email:
        type: string
        pattern: ^.+@.+\..+$
      age:
        type: integer
        minimum: 0
  Office:
    type: Person
    example: |
      {
        "name": "John",
        "email": "john@raml.org",
        "age": -1
      }
