#%RAML 1.0
tite: Test API #There's an error here.
title: Test API
types:
  User:
    properties:
      age:
        required: true
        tpe: integer #There's an error here.
      name:
        required: true
        type: string
      family:
        required: true
        type: string[]
