#%RAML 1.0
title: hola
/orgs:
  get:
    responses:
      200:
        body:
          text/html:
          application/json:
          audio/aiff:
          x-world/something:
          application/octet-stream:
          application/*:
          text/*:
          "*/*":
          audio/x-vnd.audioexplosion.mjuicemediafile:
          application/vnd.apple.installer+xml:
          application/raml+yaml:
          x-world/x-3dmf:
          text/html; charset=ISO-8859-4:
          
