#%RAML 1.0 Library
uses:
  odata: libraries/odataLibrary.raml
types:
  orders:
    (odata.remote): Orders
    properties:
      OrderID:
        type: integer
        (odata.key): true
        (odata.nullable): false
      ShipName:
        type: string
        (odata.nullable): false
        (odata.key): false
        maxLength: 10
      ShipAddress:
        type: nil | string
        (odata.nullable): true
        (odata.key): false
        required: false
  customers:
    (odata.remote): Customers
    properties:
      CustomerID:
        type: integer
        (odata.key): true
        (odata.nullable): false
      CompanyName:
        type: string
        (odata.nullable): true
        (odata.key): false
      ContactName:
        type: string
        (odata.nullable): true
        (odata.key): false
      ContactTitle:
        type: string
        (odata.nullable): true
        (odata.key): false