#%RAML 1.0 ResourceType

#This file is located at resourceTypes/collection.raml

description: A collection resource
usage: Use this to describe resource that list items
get:
  description: Retrieve all items
post:
  description: Add an item
  responses:
    201:
      <<params>>:
        Location:
