#%RAML 1.0
title: Some API

types:
    MyCustomType:
      type: number
      minimum: 2.5
      maximum: 9.30
      multipleOf: 3
      example: 6.002
    OtherCustomType:
      type: number
      minimum: 2.5
      maximum: 5.3
      examples:
        good1: 2.5
        good2: 5.3
        bad1: 2.4
        bad2: 5.4

