#%RAML 1.0
title: Example API
version: v1
resourceTypes:
  collection:
    usage: This resourceType should be used for any collection of items
    description: The collection of <<resourcePathName>>
    get:
      description: Get all <<resourcePathName>>, optionally filtered
    post?:
      description: Create a new <<resourcePathName | !singularize>>
    delete?:
      description: Delete a <<resourcePathName | !singularize>>

/users:
  type: collection
  post: