#%RAML 1.0
version: api
title: price-ticketing-xp
documentation:
 - title: price-ticketing-xp
   content: |
     Welcome to the price-ticketing-xp Documentation.

baseUri: https://price-ticketing-xp-apps.de-c1.cloudhub.io/api

uses:
  candaCommons: exchange_modules/6b05fd51-2fe5-4078-b1a1-83d16894bf76/canda-commons/1.0.8/canda-commons.raml

securedBy: [candaCommons.basicAuth]

/suppliers:
  description: The resource provides the API for the supplier.
  /shipmentTicketRequests:
    description: This resource provides ticket print information for multiple companies based on the shipment attributes of the purchase order.
    is: [ candaCommons.client-id-required ]
    post:
      description: Request data via shipment attributes.
      body:
        application/json:
          example: !include ref/supplier/shipment-ticket-request-example.json
          type: !include ref/supplier/shipment-ticket-request-schema.json
      responses:
        200:
          body:
            application/json:
              example: !include ref/supplier/ticket-print-information-example.json
              type: !include ref/supplier/ticket-print-information-schema.json

    /{ticketRequestId}:
      description: This resource provides amend functionality for an existing ticket request.
      is: [ candaCommons.client-id-required ]
      uriParameters:
        ticketRequestId:
          description: ticketRequestId
          type: string
          minLength: 32
          maxLength: 32
          required: true
          example: "567a5eae74d543bcadbfeb165c37a0e6"
      get:
        description: Retrieve updated ticket print information for the given ticketRequestId
        responses:
          200:
            body:
              application/json:
                example: !include ref/supplier/ticket-print-information-example.json
                type: !include ref/supplier/ticket-print-information-schema.json

      /statusChanges:
        description: Change the status for the given ticketRequestId
        is: [ candaCommons.client-id-required ]
        post:
          body:
            application/json:
              example: !include ref/supplier/ticket-request-status-change-example.json
              type: !include ref/supplier/ticket-request-status-change-schema.json
          responses:
            200:
              body:
                application/json:
                  example: !include ref/supplier/ticket-request-status-change-response-example.json
                  type: !include ref/supplier/ticket-request-status-change-response-schema.json


/distributionCenters:
  description: The resource provides the API for the distribution center.
  /itemNumberTicketRequests:
    description: This resource provides ticket print information for a single company based on the itemnumber of the purchase order.
    is: [ candaCommons.client-id-required ]
    post:
      description: Request data via item number.
      body:
        application/json:
          example: !include ref/dc/itemnumber-ticket-request-example.json
          type: !include ref/dc/itemnumber-ticket-request-schema.json
      responses:
        200:
          body:
            application/json:
              example: !include ref/dc/ticket-print-information-example.json
              type: !include ref/dc/ticket-print-information-schema.json

  /shipmentTicketRequests:
    description: This resource provides ticket print information for multiple companies based on the shipment attributes of the purchase order.
    is: [ candaCommons.client-id-required ]
    post:
      description: Request data via shipment attributes.
      body:
        application/json:
          example: !include ref/dc/shipment-ticket-request-example.json
          type: !include ref/dc/shipment-ticket-request-schema.json
      responses:
        200:
          body:
            application/json:
              example: !include ref/dc/ticket-print-information-example.json
              type: !include ref/dc/ticket-print-information-schema.json


/logLevels/{loggerName}:
  type: candaCommons.logLevel
  is: [ candaCommons.client-id-required ]
/ping:
  type: candaCommons.ping
  is: [ candaCommons.client-id-required ]
