#%RAML 1.0
title: master

types:
    scalar:
        type: string
        examples:
            first: primo
            second: secondo
    location:
        properties:
            lat: number
            long: number
        example:
            lat: -40.8
            long: -65.1
