#%RAML 1.0
title: simple object
types:
  root:
    properties:
      name: string
      friend:
        type: object
        properties:
          name: string
/res:
  get:
    body:
      application/xml:
          type: root
          example: |
            <root>
              <name>robert</name>
              <friend>
                <name>eddard</name>
              </friend>
              <my-custom-xml>with-custom-value</my-custom-xml>
            </root>