#%RAML 1.0
title: null type
types:
    User:
        properties:
            name:
            middlename: nil
            lastname: null
        examples:
            valid:
                name: tim
                middlename:
                lastname: duncan
            wrong-type:
                name: tim
                middlename: x
                lastname:
            missing-field:
                name: tim
                lastname: duncan
