#%RAML 1.0
title: master
baseUri: http://api.com/master

types:
    User:
        properties:
            name: string
            age?: integer
        examples:
            tato:
                name: tato
                age: 88
            pepo:
                name: pepo
                weight: 70
